### PR TITLE
PR for #42

### PR DESCRIPTION
**Pull request by COil**

### CODE REVIEW

**Comment by COil** [comment]
Didn't launched nor added tests.

**Comment by Oliboy50** [comment]
please fix the test which "should return null"

> => M6Web\Bundle\RedisBundle\Tests\Units\Redis\RedisSessionHandler::testReadWrite():
In file /home/travis/build/M6Web/RedisBundle/src/Tests/Units/Redis/RedisSessionHandler.php on line 85, mageekguy\atoum\asserters\variable() failed: string(0) '' is not null

**Comment by Oliboy50** [comment]
I personally don't use `Redis` as session manager... so... just to be sure... does this PR fix it for you? :man_dancing:

**Comment by omansour** [comment]
some tests are failing :( ?

**Comment by COil** [comment]
Sorry I don't have the bundle and test env anymore, so `isNull` has to be replaced with `isString`?

**Comment by Oliboy50** [comment]
@COil replaced with `isIdenticalTo('')`

**Comment by Oliboy50** [comment]
`isNull()` also has to be replaced with `isIdenticalTo('')` at line 90  🤕

**Pull request closed without merging**
